name: Pull Request
on: pull_request
jobs:
  build:
    name: (Pull Request) Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the git branch
        uses: actions/checkout@v2.3.2
        with:
          lfs: true
      - name: Build the Docker image
        run: docker build --no-cache .
  lint:
    name: (Pull Request) Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the git branch
        uses: actions/checkout@v2.3.2
        with:
          lfs: true
      - name: Build the Docker image
        run: docker build --no-cache -t evernaut/base:0.0.0 .
      - name: Npm Install
        run: docker run -t --mount src="$(pwd)",target="/opt/evernaut",type="bind" evernaut/base:0.0.0 bash -c 'npm ci --silent'
      - name: Lint
        run: docker run -t --mount src="$(pwd)",target="/opt/evernaut",type="bind" evernaut/base:0.0.0 bash -c 'npm run lint'
